- name: TexLive| Install
  action: apt pkg={{ item }} state=latest
  with_items:
    - texlive
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-lang-cyrillic
- include: latexmk.yml tags=latexmk
